sudo: false

os:
  - linux
  - osx

language: node_js

node_js:
  - node
  - "8.6"
  - "10"
  - "9"

install:
  - npm install

script:
  - npm run test

cache:
  yarn: false
  directories:
    - node_modules
